rabbitmq:
  exchange-producer: "producer.out"
  exchange: "consumer.out"
  queue: "consumer-queue"


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    listener:
      simple:
        prefetch: 10

server:
  servlet:
    context-path: /pull/api/v1
  port: 5990