version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.0-management
    ports:
      - 15672:15672
      - 5672:5672
      - 4369:4369
      - 25672:25672
      - 35197:35197
    environment:
#      RABBITMQ_USE_LONGNAME: true
      RABBITMQ_LOGS: /var/log/rabbitmq/rabbit.log
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:8080
      - 443:443
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates
#      cat etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

